import 'package:brave_steve/game/data_layer/models/eq_model/eq_model.dart';

enum ItemSet {
  set1,
  set2,
  set3,
}

enum Rarity {
  common,
  uncommon,
  rare,
  epic,
  legendary,
  mithic,
}

class Items {
  static const Map<ItemSet, Map<ItemTypeModel, Map<Rarity, ItemModel>>>
      _mapItems = {
    //--
    //set - 1
    //--
    ItemSet.set1: {
      ItemTypeModel.sword: {
        Rarity.common: ItemModel(
            name: 'Drewniany Miecz',
            description: 'Dodaje 4 do ataku',
            image: 'assets/images/512px_items/miecze/set_1/m1.png',
            classItem: ItemTypeModel.sword,
            price: 10,
            attack: 4,
            armour: 0),
        Rarity.uncommon: ItemModel(
            name: 'Kamienny Miecz',
            description: 'Dodaje 5 do ataku',
            image: 'assets/images/512px_items/miecze/set_1/m2.png',
            classItem: ItemTypeModel.sword,
            price: 15,
            attack: 5,
            armour: 0),
        Rarity.rare: ItemModel(
            name: 'Żelazny miecz',
            description: 'Dodaje 6 do ataku',
            image: 'assets/images/512px_items/miecze/set_1/m3.png',
            classItem: ItemTypeModel.sword,
            price: 20,
            attack: 6,
            armour: 0),
        Rarity.epic: ItemModel(
            name: 'Diamentowy Miecz',
            description: 'Dodaje 7 do ataku',
            image: 'assets/images/512px_items/miecze/set_1/m4.jpg',
            classItem: ItemTypeModel.sword,
            price: 25,
            attack: 7,
            armour: 0),
        Rarity.legendary: ItemModel(
            name: 'Legendarny Miecz',
            description: 'Dodaje 10 do ataku',
            image: 'assets/images/512px_items/miecze/set_1/m5.jpg',
            classItem: ItemTypeModel.sword,
            price: 50,
            attack: 10,
            armour: 0),
        Rarity.mithic: ItemModel(
            name: 'Mityczny Miecz',
            description: 'Dodaje 15 do ataku',
            image: 'assets/images/512px_items/miecze/set_1/m6.jpg',
            classItem: ItemTypeModel.sword,
            price: 100,
            attack: 15,
            armour: 0),
      },
      ItemTypeModel.helmet: {
        Rarity.common: ItemModel(
            name: 'Skórzany Chełm',
            description: 'Dodaje 3 pancerza',
            image: 'assets/images/512px_items/hełmy/set_1/h1.jpg',
            classItem: ItemTypeModel.helmet,
            price: 10,
            attack: 0,
            armour: 3),
        Rarity.uncommon: ItemModel(
            name: 'Kolczy Chełm',
            description: 'Dodaje 5 pancerza',
            image: 'assets/images/512px_items/hełmy/set_1/h2.jpg',
            classItem: ItemTypeModel.helmet,
            price: 15,
            attack: 0,
            armour: 5),
        Rarity.rare: ItemModel(
            name: 'Żelazny Chełm',
            description: 'Dodaje 7 pancerza',
            image: 'assets/images/512px_items/hełmy/set_1/h3.jpg',
            classItem: ItemTypeModel.helmet,
            price: 20,
            attack: 0,
            armour: 7),
        Rarity.epic: ItemModel(
            name: 'Diamentowy Chełm',
            description: 'Dodaje 9 pancerza',
            image: 'assets/images/512px_items/hełmy/set_1/h4.jpg',
            classItem: ItemTypeModel.helmet,
            price: 25,
            attack: 0,
            armour: 9),
        Rarity.legendary: ItemModel(
            name: 'Legendarny Chełm',
            description: 'Dodaje 15 pancerza',
            image: 'assets/images/512px_items/hełmy/set_1/h5.jpg',
            classItem: ItemTypeModel.helmet,
            price: 50,
            attack: 0,
            armour: 15),
        Rarity.mithic: ItemModel(
            name: 'Mityczny Chełm',
            description: 'Dodaje 20 pancerza',
            image: 'assets/images/512px_items/hełmy/set_1/h6.jpg',
            classItem: ItemTypeModel.helmet,
            price: 100,
            attack: 0,
            armour: 20),
      },
      ItemTypeModel.chestplate: {
        Rarity.common: ItemModel(
            name: 'Skórzany Napierśnik',
            description: 'Dodaje 8 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_1/n1.png',
            classItem: ItemTypeModel.chestplate,
            price: 10,
            attack: 0,
            armour: 8),
        Rarity.uncommon: ItemModel(
            name: 'Kolczy Napierśnik',
            description: 'Dodaje 10 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_1/n2.png',
            classItem: ItemTypeModel.chestplate,
            price: 15,
            attack: 0,
            armour: 10),
        Rarity.rare: ItemModel(
            name: 'Żelazny Napierśnik',
            description: 'Dodaje 12 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_1/n3.png',
            classItem: ItemTypeModel.chestplate,
            price: 20,
            attack: 0,
            armour: 12),
        Rarity.epic: ItemModel(
            name: 'Diamentowy Napierśnik',
            description: 'Dodaje 14 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_1/n4.png',
            classItem: ItemTypeModel.chestplate,
            price: 25,
            attack: 0,
            armour: 14),
        Rarity.legendary: ItemModel(
            name: 'Legendarny Napierśnik',
            description: 'Dodaje 20 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_1/n5.png',
            classItem: ItemTypeModel.chestplate,
            price: 50,
            attack: 0,
            armour: 20),
        Rarity.mithic: ItemModel(
            name: 'Mityczny Napierśnik',
            description: 'Dodaje 25 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_1/n6.png',
            classItem: ItemTypeModel.chestplate,
            price: 100,
            attack: 0,
            armour: 25),
      },
      ItemTypeModel.pants: {
        Rarity.common: ItemModel(
            name: 'Skórzane Spodnie',
            description: 'Dodają 4 pancerza',
            image: 'assets/images/512px_items/spodnie/set_1/s1.jpg',
            classItem: ItemTypeModel.pants,
            price: 10,
            attack: 0,
            armour: 4),
        Rarity.uncommon: ItemModel(
            name: 'Kolcze Spodnie',
            description: 'Dodają 6 pancerza',
            image: 'assets/images/512px_items/spodnie/set_1/s2.jpg',
            classItem: ItemTypeModel.pants,
            price: 15,
            attack: 0,
            armour: 6),
        Rarity.rare: ItemModel(
            name: 'Żelazne Spodnie',
            description: 'Dodają 8 pancerza',
            image: 'assets/images/512px_items/spodnie/set_1/s3.jpg',
            classItem: ItemTypeModel.pants,
            price: 20,
            attack: 0,
            armour: 8),
        Rarity.epic: ItemModel(
            name: 'Diamentowe Spodnie',
            description: 'Dodają 10 pancerza',
            image: 'assets/images/512px_items/spodnie/set_1/s4.jpg',
            classItem: ItemTypeModel.pants,
            price: 25,
            attack: 0,
            armour: 10),
        Rarity.legendary: ItemModel(
            name: 'Legendarny Spodnie',
            description: 'Dodają 15 pancerza',
            image: 'assets/images/512px_items/spodnie/set_1/s5.png',
            classItem: ItemTypeModel.pants,
            price: 50,
            attack: 0,
            armour: 15),
        Rarity.mithic: ItemModel(
            name: 'Mityczne Spodnie',
            description: 'Dodają 20 pancerza',
            image: 'assets/images/512px_items/spodnie/set_1/s6.png',
            classItem: ItemTypeModel.pants,
            price: 100,
            attack: 0,
            armour: 20),
      },
      ItemTypeModel.boots: {
        Rarity.common: ItemModel(
            name: 'Skórzane Buty',
            description: 'Dodają 1 pancerza',
            image: 'assets/images/512px_items/buty/set_1/b1.jpg',
            classItem: ItemTypeModel.boots,
            price: 10,
            attack: 0,
            armour: 1),
        Rarity.uncommon: ItemModel(
            name: 'Kolcze Buty',
            description: 'Dodają 3 pancerza',
            image: 'assets/images/512px_items/buty/set_1/b2.jpg',
            classItem: ItemTypeModel.boots,
            price: 15,
            attack: 0,
            armour: 3),
        Rarity.rare: ItemModel(
            name: 'Żelazne Buty',
            description: 'Dodają 5 pancerza',
            image: 'assets/images/512px_items/buty/set_1/b3.jpg',
            classItem: ItemTypeModel.boots,
            price: 20,
            attack: 0,
            armour: 5),
        Rarity.epic: ItemModel(
            name: 'Diamentowe Buty',
            description: 'Dodają 7 pancerza',
            image: 'assets/images/512px_items/buty/set_1/b4.jpg',
            classItem: ItemTypeModel.boots,
            price: 25,
            attack: 0,
            armour: 7),
        Rarity.legendary: ItemModel(
            name: 'Legendarny Buty',
            description: 'Dodają 10 pancerza',
            image: 'assets/images/512px_items/buty/set_1/b5.jpg',
            classItem: ItemTypeModel.boots,
            price: 50,
            attack: 0,
            armour: 10),
        Rarity.mithic: ItemModel(
            name: 'Mityczne Buty',
            description: 'Dodają 15 pancerza',
            image: 'assets/images/512px_items/buty/set_1/b6.jpg',
            classItem: ItemTypeModel.boots,
            price: 100,
            attack: 0,
            armour: 15),
      }
    },
    //--
    //set - 2
    //--
    ItemSet.set2: {
      ItemTypeModel.sword: {
        Rarity.common: ItemModel(
            name: 'Drewniany Miecz',
            description: 'Dodaje 4 do ataku',
            image: 'assets/images/512px_items/miecze/set_2/m1.png',
            classItem: ItemTypeModel.sword,
            price: 10,
            attack: 4,
            armour: 0),
        Rarity.uncommon: ItemModel(
            name: 'Kamienny Miecz',
            description: 'Dodaje 5 do ataku',
            image: 'assets/images/512px_items/miecze/set_2/m2.png',
            classItem: ItemTypeModel.sword,
            price: 15,
            attack: 5,
            armour: 0),
        Rarity.rare: ItemModel(
            name: 'Żelazny miecz',
            description: 'Dodaje 6 do ataku',
            image: 'assets/images/512px_items/miecze/set_2/m3.png',
            classItem: ItemTypeModel.sword,
            price: 20,
            attack: 6,
            armour: 0),
        Rarity.epic: ItemModel(
            name: 'Diamentowy Miecz',
            description: 'Dodaje 7 do ataku',
            image: 'assets/images/512px_items/miecze/set_2/m4.png',
            classItem: ItemTypeModel.sword,
            price: 25,
            attack: 7,
            armour: 0),
        Rarity.legendary: ItemModel(
            name: 'Legendarny Miecz',
            description: 'Dodaje 10 do ataku',
            image: 'assets/images/512px_items/miecze/set_2/m5.png',
            classItem: ItemTypeModel.sword,
            price: 50,
            attack: 10,
            armour: 0),
        Rarity.mithic: ItemModel(
            name: 'Mityczny Miecz',
            description: 'Dodaje 15 do ataku',
            image: 'assets/images/512px_items/miecze/set_2/m6.png',
            classItem: ItemTypeModel.sword,
            price: 100,
            attack: 15,
            armour: 0),
      },
      ItemTypeModel.helmet: {
        Rarity.common: ItemModel(
            name: 'Skórzany Chełm',
            description: 'Dodaje 3 pancerza',
            image: 'assets/images/512px_items/hełmy/set_2/h1.png',
            classItem: ItemTypeModel.helmet,
            price: 10,
            attack: 0,
            armour: 3),
        Rarity.uncommon: ItemModel(
            name: 'Kolczy Chełm',
            description: 'Dodaje 5 pancerza',
            image: 'assets/images/512px_items/hełmy/set_2/h2.png',
            classItem: ItemTypeModel.helmet,
            price: 15,
            attack: 0,
            armour: 5),
        Rarity.rare: ItemModel(
            name: 'Żelazny Chełm',
            description: 'Dodaje 7 pancerza',
            image: 'assets/images/512px_items/hełmy/set_2/h3.png',
            classItem: ItemTypeModel.helmet,
            price: 20,
            attack: 0,
            armour: 7),
        Rarity.epic: ItemModel(
            name: 'Diamentowy Chełm',
            description: 'Dodaje 9 pancerza',
            image: 'assets/images/512px_items/hełmy/set_2/h4.png',
            classItem: ItemTypeModel.helmet,
            price: 25,
            attack: 0,
            armour: 9),
        Rarity.legendary: ItemModel(
            name: 'Legendarny Chełm',
            description: 'Dodaje 15 pancerza',
            image: 'assets/images/512px_items/hełmy/set_2/h5.png',
            classItem: ItemTypeModel.helmet,
            price: 50,
            attack: 0,
            armour: 15),
        Rarity.mithic: ItemModel(
            name: 'Mityczny Chełm',
            description: 'Dodaje 20 pancerza',
            image: 'assets/images/512px_items/hełmy/set_2/h6.png',
            classItem: ItemTypeModel.helmet,
            price: 100,
            attack: 0,
            armour: 20),
      },
      ItemTypeModel.chestplate: {
        Rarity.common: ItemModel(
            name: 'Skórzany Napierśnik',
            description: 'Dodaje 8 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_2/n1.png',
            classItem: ItemTypeModel.chestplate,
            price: 10,
            attack: 0,
            armour: 8),
        Rarity.uncommon: ItemModel(
            name: 'Kolczy Napierśnik',
            description: 'Dodaje 10 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_2/n2.png',
            classItem: ItemTypeModel.chestplate,
            price: 15,
            attack: 0,
            armour: 10),
        Rarity.rare: ItemModel(
            name: 'Żelazny Napierśnik',
            description: 'Dodaje 12 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_2/n3.png',
            classItem: ItemTypeModel.chestplate,
            price: 20,
            attack: 0,
            armour: 12),
        Rarity.epic: ItemModel(
            name: 'Diamentowy Napierśnik',
            description: 'Dodaje 14 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_2/n4.png',
            classItem: ItemTypeModel.chestplate,
            price: 25,
            attack: 0,
            armour: 14),
        Rarity.legendary: ItemModel(
            name: 'Legendarny Napierśnik',
            description: 'Dodaje 20 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_2/n5.jpeg',
            classItem: ItemTypeModel.chestplate,
            price: 50,
            attack: 0,
            armour: 20),
        Rarity.mithic: ItemModel(
            name: 'Mityczny Napierśnik',
            description: 'Dodaje 25 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_2/n6.png',
            classItem: ItemTypeModel.chestplate,
            price: 100,
            attack: 0,
            armour: 25),
      },
      ItemTypeModel.pants: {
        Rarity.common: ItemModel(
            name: 'Skórzane Spodnie',
            description: 'Dodają 4 pancerza',
            image: 'assets/images/512px_items/spodnie/set_2/s1.jpg',
            classItem: ItemTypeModel.pants,
            price: 10,
            attack: 0,
            armour: 4),
        Rarity.uncommon: ItemModel(
            name: 'Kolcze Spodnie',
            description: 'Dodają 6 pancerza',
            image: 'assets/images/512px_items/spodnie/set_2/s2.jpg',
            classItem: ItemTypeModel.pants,
            price: 15,
            attack: 0,
            armour: 6),
        Rarity.rare: ItemModel(
            name: 'Żelazne Spodnie',
            description: 'Dodają 8 pancerza',
            image: 'assets/images/512px_items/spodnie/set_2/s3.jpg',
            classItem: ItemTypeModel.pants,
            price: 20,
            attack: 0,
            armour: 8),
        Rarity.epic: ItemModel(
            name: 'Diamentowe Spodnie',
            description: 'Dodają 10 pancerza',
            image: 'assets/images/512px_items/spodnie/set_2/s4.jpg',
            classItem: ItemTypeModel.pants,
            price: 25,
            attack: 0,
            armour: 10),
        Rarity.legendary: ItemModel(
            name: 'Legendarny Spodnie',
            description: 'Dodają 15 pancerza',
            image: 'assets/images/512px_items/spodnie/set_2/s5.jpg',
            classItem: ItemTypeModel.pants,
            price: 50,
            attack: 0,
            armour: 15),
        Rarity.mithic: ItemModel(
            name: 'Mityczne Spodnie',
            description: 'Dodają 20 pancerza',
            image: 'assets/images/512px_items/spodnie/set_2/s6.jpg',
            classItem: ItemTypeModel.pants,
            price: 100,
            attack: 0,
            armour: 20),
      },
      ItemTypeModel.boots: {
        Rarity.common: ItemModel(
            name: 'Skórzane Buty',
            description: 'Dodają 1 pancerza',
            image: 'assets/images/512px_items/buty/set_2/b1.png',
            classItem: ItemTypeModel.boots,
            price: 10,
            attack: 0,
            armour: 1),
        Rarity.uncommon: ItemModel(
            name: 'Kolcze Buty',
            description: 'Dodają 3 pancerza',
            image: 'assets/images/512px_items/buty/set_2/b2.png',
            classItem: ItemTypeModel.boots,
            price: 15,
            attack: 0,
            armour: 3),
        Rarity.rare: ItemModel(
            name: 'Żelazne Buty',
            description: 'Dodają 5 pancerza',
            image: 'assets/images/512px_items/buty/set_2/b3.png',
            classItem: ItemTypeModel.boots,
            price: 20,
            attack: 0,
            armour: 5),
        Rarity.epic: ItemModel(
            name: 'Diamentowe Buty',
            description: 'Dodają 7 pancerza',
            image: 'assets/images/512px_items/buty/set_2/b4.png',
            classItem: ItemTypeModel.boots,
            price: 25,
            attack: 0,
            armour: 7),
        Rarity.legendary: ItemModel(
            name: 'Legendarny Buty',
            description: 'Dodają 10 pancerza',
            image: 'assets/images/512px_items/buty/set_2/b5.png',
            classItem: ItemTypeModel.boots,
            price: 50,
            attack: 0,
            armour: 10),
        Rarity.mithic: ItemModel(
            name: 'Mityczne Buty',
            description: 'Dodają 15 pancerza',
            image: 'assets/images/512px_items/buty/set_2/b6.png',
            classItem: ItemTypeModel.boots,
            price: 100,
            attack: 0,
            armour: 15),
      }
    },
    //--
    //set - 3
    //--
    ItemSet.set3: {
      ItemTypeModel.sword: {
        Rarity.common: ItemModel(
            name: 'Drewniany Miecz',
            description: 'Dodaje 4 do ataku',
            image: 'assets/images/512px_items/miecze/set_3/m1.png',
            classItem: ItemTypeModel.sword,
            price: 10,
            attack: 4,
            armour: 0),
        Rarity.uncommon: ItemModel(
            name: 'Kamienny Miecz',
            description: 'Dodaje 5 do ataku',
            image: 'assets/images/512px_items/miecze/set_3/m2.png',
            classItem: ItemTypeModel.sword,
            price: 15,
            attack: 5,
            armour: 0),
        Rarity.rare: ItemModel(
            name: 'Żelazny miecz',
            description: 'Dodaje 6 do ataku',
            image: 'assets/images/512px_items/miecze/set_3/m3.jpg',
            classItem: ItemTypeModel.sword,
            price: 20,
            attack: 6,
            armour: 0),
        Rarity.epic: ItemModel(
            name: 'Diamentowy Miecz',
            description: 'Dodaje 7 do ataku',
            image: 'assets/images/512px_items/miecze/set_3/m4.png',
            classItem: ItemTypeModel.sword,
            price: 25,
            attack: 7,
            armour: 0),
        Rarity.legendary: ItemModel(
            name: 'Legendarny Miecz',
            description: 'Dodaje 10 do ataku',
            image: 'assets/images/512px_items/miecze/set_3/m5.png',
            classItem: ItemTypeModel.sword,
            price: 50,
            attack: 10,
            armour: 0),
        Rarity.mithic: ItemModel(
            name: 'Mityczny Miecz',
            description: 'Dodaje 15 do ataku',
            image: 'assets/images/512px_items/miecze/set_3/m6.jpg',
            classItem: ItemTypeModel.sword,
            price: 100,
            attack: 15,
            armour: 0),
      },
      ItemTypeModel.helmet: {
        Rarity.common: ItemModel(
            name: 'Skórzany Chełm',
            description: 'Dodaje 3 pancerza',
            image: 'assets/images/512px_items/hełmy/set_3/h1.png',
            classItem: ItemTypeModel.helmet,
            price: 10,
            attack: 0,
            armour: 3),
        Rarity.uncommon: ItemModel(
            name: 'Kolczy Chełm',
            description: 'Dodaje 5 pancerza',
            image: 'assets/images/512px_items/hełmy/set_3/h2.jpeg',
            classItem: ItemTypeModel.helmet,
            price: 15,
            attack: 0,
            armour: 5),
        Rarity.rare: ItemModel(
            name: 'Żelazny Chełm',
            description: 'Dodaje 7 pancerza',
            image: 'assets/images/512px_items/hełmy/set_3/h3.jpeg',
            classItem: ItemTypeModel.helmet,
            price: 20,
            attack: 0,
            armour: 7),
        Rarity.epic: ItemModel(
            name: 'Diamentowy Chełm',
            description: 'Dodaje 9 pancerza',
            image: 'assets/images/512px_items/hełmy/set_3/h4.jpeg',
            classItem: ItemTypeModel.helmet,
            price: 25,
            attack: 0,
            armour: 9),
        Rarity.legendary: ItemModel(
            name: 'Legendarny Chełm',
            description: 'Dodaje 15 pancerza',
            image: 'assets/images/512px_items/hełmy/set_3/h5.jpg',
            classItem: ItemTypeModel.helmet,
            price: 50,
            attack: 0,
            armour: 15),
        Rarity.mithic: ItemModel(
            name: 'Mityczny Chełm',
            description: 'Dodaje 20 pancerza',
            image: 'assets/images/512px_items/hełmy/set_3/h6.jpg',
            classItem: ItemTypeModel.helmet,
            price: 100,
            attack: 0,
            armour: 20),
      },
      ItemTypeModel.chestplate: {
        Rarity.common: ItemModel(
            name: 'Skórzany Napierśnik',
            description: 'Dodaje 8 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_3/n1.jpg',
            classItem: ItemTypeModel.chestplate,
            price: 10,
            attack: 0,
            armour: 8),
        Rarity.uncommon: ItemModel(
            name: 'Kolczy Napierśnik',
            description: 'Dodaje 10 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_3/n2.jpg',
            classItem: ItemTypeModel.chestplate,
            price: 15,
            attack: 0,
            armour: 10),
        Rarity.rare: ItemModel(
            name: 'Żelazny Napierśnik',
            description: 'Dodaje 12 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_3/n3.jpg',
            classItem: ItemTypeModel.chestplate,
            price: 20,
            attack: 0,
            armour: 12),
        Rarity.epic: ItemModel(
            name: 'Diamentowy Napierśnik',
            description: 'Dodaje 14 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_3/n4.jpg',
            classItem: ItemTypeModel.chestplate,
            price: 25,
            attack: 0,
            armour: 14),
        Rarity.legendary: ItemModel(
            name: 'Legendarny Napierśnik',
            description: 'Dodaje 20 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_3/n5.png',
            classItem: ItemTypeModel.chestplate,
            price: 50,
            attack: 0,
            armour: 20),
        Rarity.mithic: ItemModel(
            name: 'Mityczny Napierśnik',
            description: 'Dodaje 25 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_3/n6.png',
            classItem: ItemTypeModel.chestplate,
            price: 100,
            attack: 0,
            armour: 25),
      },
      ItemTypeModel.pants: {
        Rarity.common: ItemModel(
            name: 'Skórzane Spodnie',
            description: 'Dodają 4 pancerza',
            image: 'assets/images/512px_items/spodnie/set_3/s1.jpg',
            classItem: ItemTypeModel.pants,
            price: 10,
            attack: 0,
            armour: 4),
        Rarity.uncommon: ItemModel(
            name: 'Kolcze Spodnie',
            description: 'Dodają 6 pancerza',
            image: 'assets/images/512px_items/spodnie/set_3/s2.jpg',
            classItem: ItemTypeModel.pants,
            price: 15,
            attack: 0,
            armour: 6),
        Rarity.rare: ItemModel(
            name: 'Żelazne Spodnie',
            description: 'Dodają 8 pancerza',
            image: 'assets/images/512px_items/spodnie/set_3/s3.png',
            classItem: ItemTypeModel.pants,
            price: 20,
            attack: 0,
            armour: 8),
        Rarity.epic: ItemModel(
            name: 'Diamentowe Spodnie',
            description: 'Dodają 10 pancerza',
            image: 'assets/images/512px_items/spodnie/set_3/s4.jpg',
            classItem: ItemTypeModel.pants,
            price: 25,
            attack: 0,
            armour: 10),
        Rarity.legendary: ItemModel(
            name: 'Legendarny Spodnie',
            description: 'Dodają 15 pancerza',
            image: 'assets/images/512px_items/spodnie/set_3/s5.jpg',
            classItem: ItemTypeModel.pants,
            price: 50,
            attack: 0,
            armour: 15),
        Rarity.mithic: ItemModel(
            name: 'Mityczne Spodnie',
            description: 'Dodają 20 pancerza',
            image: 'assets/images/512px_items/spodnie/set_3/s6.jpg',
            classItem: ItemTypeModel.pants,
            price: 100,
            attack: 0,
            armour: 20),
      },
      ItemTypeModel.boots: {
        Rarity.common: ItemModel(
            name: 'Skórzane Buty',
            description: 'Dodają 1 pancerza',
            image: 'assets/images/512px_items/buty/set_3/b1.jpg',
            classItem: ItemTypeModel.boots,
            price: 10,
            attack: 0,
            armour: 1),
        Rarity.uncommon: ItemModel(
            name: 'Kolcze Buty',
            description: 'Dodają 3 pancerza',
            image: 'assets/images/512px_items/buty/set_3/b2.jpg',
            classItem: ItemTypeModel.boots,
            price: 15,
            attack: 0,
            armour: 3),
        Rarity.rare: ItemModel(
            name: 'Żelazne Buty',
            description: 'Dodają 5 pancerza',
            image: 'assets/images/512px_items/buty/set_3/b3.jpg',
            classItem: ItemTypeModel.boots,
            price: 20,
            attack: 0,
            armour: 5),
        Rarity.epic: ItemModel(
            name: 'Diamentowe Buty',
            description: 'Dodają 7 pancerza',
            image: 'assets/images/512px_items/buty/set_3/b4.jpg',
            classItem: ItemTypeModel.boots,
            price: 25,
            attack: 0,
            armour: 7),
        Rarity.legendary: ItemModel(
            name: 'Legendarny Buty',
            description: 'Dodają 10 pancerza',
            image: 'assets/images/512px_items/buty/set_3/b5.jpg',
            classItem: ItemTypeModel.boots,
            price: 50,
            attack: 0,
            armour: 10),
        Rarity.mithic: ItemModel(
            name: 'Mityczne Buty',
            description: 'Dodają 15 pancerza',
            image: 'assets/images/512px_items/buty/set_3/b6.jpg',
            classItem: ItemTypeModel.boots,
            price: 100,
            attack: 0,
            armour: 15),
      }
    }
  };

  ItemModel getItem(ItemSet itemSet, ItemTypeModel itemType, Rarity rarity) {
    return _mapItems[itemSet]![itemType]![rarity]!;
  }
}
