import 'package:brave_steve/core/modules/models/enums.dart';
import 'package:brave_steve/modules/eq/model/eq_model.dart';
enum ItemSet {
  set1,
  set2,
  set3,
  free
}

enum Rarity {
  common,
  uncommon,
  rare,
  epic,
  legendary,
  mithic,
}

class Items {
  int maxLevelCommon = 5;
  int maxLevelUncommon = 10;
  int maxLevelRare = 15;
  int maxLevelEpic = 25;
  int maxLevelLegendary = 30;
  static const Map<ItemSet, Map<ItemTypeModel, Map<Rarity, ItemModel>>>
      _mapItems = {
    //--
    //set - 1 zestaw dla fanatyka
    //--
    ItemSet.set1: {
      ItemTypeModel.sword: {
        Rarity.common: ItemModel(
            name: 'Miecz fanatyka I',
            description: 'Dodaje 4 do ataku',
            image: 'assets/images/512px_items/miecze/set_1/m1.png',
            classItem: ItemTypeModel.sword,
            price: 10,
            attack: 4,
            itemRarity: 'common',
            upgradePrice: 20,
            numerZestawu: 1),
        Rarity.uncommon: ItemModel(
            name: 'Miecz fanatyka II',
            description: 'Dodaje 5 do ataku',
            image: 'assets/images/512px_items/miecze/set_1/m2.png',
            classItem: ItemTypeModel.sword,
            price: 15,
            attack: 5,
            itemRarity: 'uncommon',
            upgradePrice: 20,
            numerZestawu: 1),
        Rarity.rare: ItemModel(
            name: 'Miecz fanatyka III',
            description: 'Dodaje 6 do ataku',
            image: 'assets/images/512px_items/miecze/set_1/m3.png',
            classItem: ItemTypeModel.sword,
            price: 20,
            attack: 6,
            itemRarity: 'rare',
            upgradePrice: 20,
            numerZestawu: 1),
        Rarity.epic: ItemModel(
            name: 'Miecz fanatyka IV',
            description: 'Dodaje 7 do ataku',
            image: 'assets/images/512px_items/miecze/set_1/m4.jpg',
            classItem: ItemTypeModel.sword,
            price: 25,
            attack: 7,
            itemRarity: 'epic',
            upgradePrice: 20,
            numerZestawu: 1),
        Rarity.legendary: ItemModel(
            name: 'Miecz fanatyka V',
            description: 'Dodaje 10 do ataku',
            image: 'assets/images/512px_items/miecze/set_1/m5.jpg',
            classItem: ItemTypeModel.sword,
            price: 50,
            attack: 10,
            itemRarity: 'legendary',
            upgradePrice: 20,
            numerZestawu: 1),
        Rarity.mithic: ItemModel(
            name: 'Miecz fanatyka VI',
            description: 'Dodaje 15 do ataku',
            image: 'assets/images/512px_items/miecze/set_1/m6.jpg',
            classItem: ItemTypeModel.sword,
            price: 100,
            attack: 15,
            itemRarity: 'mithic',
            upgradePrice: 20,
            numerZestawu: 1),
      },
      ItemTypeModel.helmet: {
        Rarity.common: ItemModel(
            name: 'Chełm fanatyka I',
            description: 'Dodaje 3 pancerza',
            image: 'assets/images/512px_items/hełmy/set_1/h1.jpg',
            classItem: ItemTypeModel.helmet,
            price: 10,
            armour: 3,
            itemRarity: 'common',
            upgradePrice: 20,
            numerZestawu: 1),
        Rarity.uncommon: ItemModel(
            name: 'Chełm fanatyka II',
            description: 'Dodaje 5 pancerza',
            image: 'assets/images/512px_items/hełmy/set_1/h2.jpg',
            classItem: ItemTypeModel.helmet,
            price: 15,
            armour: 5,
            itemRarity: 'uncommon',
            upgradePrice: 20,
            numerZestawu: 1),
        Rarity.rare: ItemModel(
            name: 'Chełm fanatyka III',
            description: 'Dodaje 7 pancerza',
            image: 'assets/images/512px_items/hełmy/set_1/h3.jpg',
            classItem: ItemTypeModel.helmet,
            price: 20,
            armour: 7,
            itemRarity: 'rare',
            upgradePrice: 20,
            numerZestawu: 1),
        Rarity.epic: ItemModel(
            name: 'Chełm fanatyka IV',
            description: 'Dodaje 9 pancerza',
            image: 'assets/images/512px_items/hełmy/set_1/h4.jpg',
            classItem: ItemTypeModel.helmet,
            price: 25,
            armour: 9,
            itemRarity: 'epic',
            upgradePrice: 20,
            numerZestawu: 1),
        Rarity.legendary: ItemModel(
            name: 'Chełm fanatyka V',
            description: 'Dodaje 15 pancerza',
            image: 'assets/images/512px_items/hełmy/set_1/h5.jpg',
            classItem: ItemTypeModel.helmet,
            price: 50,
            armour: 15,
            itemRarity: 'legendary',
            upgradePrice: 20,
            numerZestawu: 1),
        Rarity.mithic: ItemModel(
            name: 'Chełm fanatyka VI',
            description: 'Dodaje 20 pancerza',
            image: 'assets/images/512px_items/hełmy/set_1/h6.jpg',
            classItem: ItemTypeModel.helmet,
            price: 100,
            armour: 20,
            itemRarity: 'mithic',
            upgradePrice: 20,
            numerZestawu: 1),
      },
      ItemTypeModel.chestplate: {
        Rarity.common: ItemModel(
            name: 'Napierśnik fanatyka I',
            description: 'Dodaje 8 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_1/n1.png',
            classItem: ItemTypeModel.chestplate,
            price: 10,
            armour: 8,
            itemRarity: 'common',
            upgradePrice: 20,
            numerZestawu: 1),
        Rarity.uncommon: ItemModel(
            name: 'Napierśnik fanatyka II',
            description: 'Dodaje 10 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_1/n2.png',
            classItem: ItemTypeModel.chestplate,
            price: 15,
            armour: 10,
            itemRarity: 'uncommon',
            upgradePrice: 20,
            numerZestawu: 1),
        Rarity.rare: ItemModel(
            name: 'Napierśnik fanatyka III',
            description: 'Dodaje 12 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_1/n3.png',
            classItem: ItemTypeModel.chestplate,
            price: 20,
            armour: 12,
            itemRarity: 'rare',
            upgradePrice: 20,
            numerZestawu: 1),
        Rarity.epic: ItemModel(
            name: 'Napierśnik fanatyka IV',
            description: 'Dodaje 14 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_1/n4.png',
            classItem: ItemTypeModel.chestplate,
            price: 25,
            armour: 14,
            itemRarity: 'epic',
            upgradePrice: 20,
            numerZestawu: 1),
        Rarity.legendary: ItemModel(
            name: 'Napierśnik fanatyka V',
            description: 'Dodaje 20 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_1/n5.png',
            classItem: ItemTypeModel.chestplate,
            price: 50,
            attack: 0,
            armour: 20,
            itemRarity: 'legendary',
            upgradePrice: 20),
        Rarity.mithic: ItemModel(
            name: 'Napierśnik fanatyka VI',
            description: 'Dodaje 25 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_1/n6.png',
            classItem: ItemTypeModel.chestplate,
            price: 100,
            armour: 25,
            itemRarity: 'mithic',
            upgradePrice: 20,
            numerZestawu: 1),
      },
      ItemTypeModel.pants: {
        Rarity.common: ItemModel(
            name: 'Spodnie fanatyka I',
            description: 'Dodają 4 pancerza',
            image: 'assets/images/512px_items/spodnie/set_1/s1.jpg',
            classItem: ItemTypeModel.pants,
            price: 10,
            armour: 4,
            itemRarity: 'common',
            upgradePrice: 20,
            numerZestawu: 1),
        Rarity.uncommon: ItemModel(
            name: 'Spodnie fanatyka II',
            description: 'Dodają 6 pancerza',
            image: 'assets/images/512px_items/spodnie/set_1/s2.jpg',
            classItem: ItemTypeModel.pants,
            price: 15,
            armour: 6,
            itemRarity: 'uncommon',
            upgradePrice: 20,
            numerZestawu: 1),
        Rarity.rare: ItemModel(
            name: 'Spodnie fanatyka III',
            description: 'Dodają 8 pancerza',
            image: 'assets/images/512px_items/spodnie/set_1/s3.jpg',
            classItem: ItemTypeModel.pants,
            price: 20,
            armour: 8,
            itemRarity: 'rare',
            upgradePrice: 20,
            numerZestawu: 1),
        Rarity.epic: ItemModel(
            name: 'Spodnie fanatyka IV',
            description: 'Dodają 10 pancerza',
            image: 'assets/images/512px_items/spodnie/set_1/s4.jpg',
            classItem: ItemTypeModel.pants,
            price: 25,
            armour: 10,
            itemRarity: 'epic',
            upgradePrice: 20,
            numerZestawu: 1),
        Rarity.legendary: ItemModel(
            name: 'Spodnie fanatyka V',
            description: 'Dodają 15 pancerza',
            image: 'assets/images/512px_items/spodnie/set_1/s5.png',
            classItem: ItemTypeModel.pants,
            price: 50,
            armour: 15,
            itemRarity: 'legendary',
            upgradePrice: 20,
            numerZestawu: 1),
        Rarity.mithic: ItemModel(
            name: 'Spodnie fanatyka VI',
            description: 'Dodają 20 pancerza',
            image: 'assets/images/512px_items/spodnie/set_1/s6.png',
            classItem: ItemTypeModel.pants,
            price: 100,
            armour: 20,
            itemRarity: 'mithic',
            upgradePrice: 20,
            numerZestawu: 1),
      },
      ItemTypeModel.boots: {
        Rarity.common: ItemModel(
            name: 'Buty fanatyka I',
            description: 'Dodają 1 pancerza',
            image: 'assets/images/512px_items/buty/set_1/b1.jpg',
            classItem: ItemTypeModel.boots,
            price: 10,
            armour: 1,
            itemRarity: 'common',
            upgradePrice: 20,
            numerZestawu: 1),
        Rarity.uncommon: ItemModel(
            name: 'Buty fanatyka II',
            description: 'Dodają 3 pancerza',
            image: 'assets/images/512px_items/buty/set_1/b2.jpg',
            classItem: ItemTypeModel.boots,
            price: 15,
            armour: 3,
            itemRarity: 'uncommon',
            upgradePrice: 20,
            numerZestawu: 1),
        Rarity.rare: ItemModel(
            name: 'Buty fanatyka III',
            description: 'Dodają 5 pancerza',
            image: 'assets/images/512px_items/buty/set_1/b3.jpg',
            classItem: ItemTypeModel.boots,
            price: 20,
            armour: 5,
            itemRarity: 'rare',
            upgradePrice: 20,
            numerZestawu: 1),
        Rarity.epic: ItemModel(
            name: 'Buty fanatyka IV',
            description: 'Dodają 7 pancerza',
            image: 'assets/images/512px_items/buty/set_1/b4.jpg',
            classItem: ItemTypeModel.boots,
            price: 25,
            armour: 7,
            itemRarity: 'epic',
            upgradePrice: 20,
            numerZestawu: 1),
        Rarity.legendary: ItemModel(
            name: 'Buty fanatyka V',
            description: 'Dodają 10 pancerza',
            image: 'assets/images/512px_items/buty/set_1/b5.jpg',
            classItem: ItemTypeModel.boots,
            price: 50,
            armour: 10,
            itemRarity: 'legendary',
            upgradePrice: 20,
            numerZestawu: 1),
        Rarity.mithic: ItemModel(
            name: 'Buty fanatyka VI',
            description: 'Dodają 15 pancerza',
            image: 'assets/images/512px_items/buty/set_1/b6.jpg',
            classItem: ItemTypeModel.boots,
            price: 100,
            armour: 15,
            itemRarity: 'mithic',
            upgradePrice: 20,
            numerZestawu: 1),
      }
    },
    //--
    //set - 2 zestaw dla paladyna
    //--
    ItemSet.set2: {
      ItemTypeModel.sword: {
        Rarity.common: ItemModel(
            name: 'Miecz paladyna I',
            description: 'Dodaje 4 do ataku',
            image: 'assets/images/512px_items/miecze/set_2/m1.png',
            classItem: ItemTypeModel.sword,
            price: 10,
            attack: 4,
            itemRarity: 'common',
            upgradePrice: 20,
            numerZestawu: 2),
        Rarity.uncommon: ItemModel(
            name: 'Miecz paladyna II',
            description: 'Dodaje 5 do ataku',
            image: 'assets/images/512px_items/miecze/set_2/m2.png',
            classItem: ItemTypeModel.sword,
            price: 15,
            attack: 5,
            itemRarity: 'uncommon',
            upgradePrice: 20,
            numerZestawu: 2),
        Rarity.rare: ItemModel(
            name: 'Miecz paladyna III',
            description: 'Dodaje 6 do ataku',
            image: 'assets/images/512px_items/miecze/set_2/m3.png',
            classItem: ItemTypeModel.sword,
            price: 20,
            attack: 6,
            itemRarity: 'rare',
            upgradePrice: 20,
            numerZestawu: 2),
        Rarity.epic: ItemModel(
            name: 'Miecz paladyna IV',
            description: 'Dodaje 7 do ataku',
            image: 'assets/images/512px_items/miecze/set_2/m4.png',
            classItem: ItemTypeModel.sword,
            price: 25,
            attack: 7,
            itemRarity: 'epic',
            upgradePrice: 20,
            numerZestawu: 2),
        Rarity.legendary: ItemModel(
            name: 'Miecz paladyna V',
            description: 'Dodaje 10 do ataku',
            image: 'assets/images/512px_items/miecze/set_2/m5.png',
            classItem: ItemTypeModel.sword,
            price: 50,
            attack: 10,
            itemRarity: 'legendary',
            upgradePrice: 20,
            numerZestawu: 2),
        Rarity.mithic: ItemModel(
            name: 'Miecz paladyna VI',
            description: 'Dodaje 15 do ataku',
            image: 'assets/images/512px_items/miecze/set_2/m6.png',
            classItem: ItemTypeModel.sword,
            price: 100,
            attack: 15,
            itemRarity: 'mithic',
            upgradePrice: 20,
            numerZestawu: 2),
      },
      ItemTypeModel.helmet: {
        Rarity.common: ItemModel(
            name: 'Chełm paladyna I',
            description: 'Dodaje 3 pancerza',
            image: 'assets/images/512px_items/hełmy/set_2/h1.png',
            classItem: ItemTypeModel.helmet,
            price: 10,
            armour: 3,
            itemRarity: 'common',
            upgradePrice: 20,
            numerZestawu: 2),
        Rarity.uncommon: ItemModel(
            name: 'Chełm paladyna II',
            description: 'Dodaje 5 pancerza',
            image: 'assets/images/512px_items/hełmy/set_2/h2.png',
            classItem: ItemTypeModel.helmet,
            price: 15,
            armour: 5,
            itemRarity: 'uncommon',
            upgradePrice: 20,
            numerZestawu: 2),
        Rarity.rare: ItemModel(
            name: 'Chełm paladyna III',
            description: 'Dodaje 7 pancerza',
            image: 'assets/images/512px_items/hełmy/set_2/h3.png',
            classItem: ItemTypeModel.helmet,
            price: 20,
            armour: 7,
            itemRarity: 'rare',
            upgradePrice: 20,
            numerZestawu: 2),
        Rarity.epic: ItemModel(
            name: 'Chełm paladyna IV',
            description: 'Dodaje 9 pancerza',
            image: 'assets/images/512px_items/hełmy/set_2/h4.png',
            classItem: ItemTypeModel.helmet,
            price: 25,
            armour: 9,
            itemRarity: 'epic',
            upgradePrice: 20,
            numerZestawu: 2),
        Rarity.legendary: ItemModel(
            name: 'Chełm paladyna V',
            description: 'Dodaje 15 pancerza',
            image: 'assets/images/512px_items/hełmy/set_2/h5.png',
            classItem: ItemTypeModel.helmet,
            price: 50,
            armour: 15,
            itemRarity: 'legendary',
            upgradePrice: 20,
            numerZestawu: 2),
        Rarity.mithic: ItemModel(
            name: 'Chełm paladyna VI',
            description: 'Dodaje 20 pancerza',
            image: 'assets/images/512px_items/hełmy/set_2/h6.png',
            classItem: ItemTypeModel.helmet,
            price: 100,
            armour: 20,
            itemRarity: 'mithic',
            upgradePrice: 20,
            numerZestawu: 2),
      },
      ItemTypeModel.chestplate: {
        Rarity.common: ItemModel(
            name: 'Spodnie paladyna I',
            description: 'Dodaje 8 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_2/n1.png',
            classItem: ItemTypeModel.chestplate,
            price: 10,
            armour: 8,
            itemRarity: 'common',
            upgradePrice: 20,
            numerZestawu: 2),
        Rarity.uncommon: ItemModel(
            name: 'Spodnie paladyna II',
            description: 'Dodaje 10 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_2/n2.png',
            classItem: ItemTypeModel.chestplate,
            price: 15,
            armour: 10,
            itemRarity: 'uncommon',
            upgradePrice: 20,
            numerZestawu: 2),
        Rarity.rare: ItemModel(
            name: 'Spodnie paladyna III',
            description: 'Dodaje 12 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_2/n3.png',
            classItem: ItemTypeModel.chestplate,
            price: 20,
            armour: 12,
            itemRarity: 'rare',
            upgradePrice: 20,
            numerZestawu: 2),
        Rarity.epic: ItemModel(
            name: 'Spodnie paladyna IV',
            description: 'Dodaje 14 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_2/n4.png',
            classItem: ItemTypeModel.chestplate,
            price: 25,
            armour: 14,
            itemRarity: 'epic',
            upgradePrice: 20,
            numerZestawu: 2),
        Rarity.legendary: ItemModel(
            name: 'Spodnie paladyna V',
            description: 'Dodaje 20 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_2/n5.jpeg',
            classItem: ItemTypeModel.chestplate,
            price: 50,
            armour: 20,
            itemRarity: 'legendary',
            upgradePrice: 20,
            numerZestawu: 2),
        Rarity.mithic: ItemModel(
            name: 'Spodnie paladyna VI',
            description: 'Dodaje 25 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_2/n6.png',
            classItem: ItemTypeModel.chestplate,
            price: 100,
            armour: 25,
            itemRarity: 'mithic',
            upgradePrice: 20,
            numerZestawu: 2),
      },
      ItemTypeModel.pants: {
        Rarity.common: ItemModel(
            name: 'Spodnie paladyna I',
            description: 'Dodają 4 pancerza',
            image: 'assets/images/512px_items/spodnie/set_2/s1.jpg',
            classItem: ItemTypeModel.pants,
            price: 10,
            armour: 4,
            itemRarity: 'common',
            upgradePrice: 20,
            numerZestawu: 2),
        Rarity.uncommon: ItemModel(
            name: 'Spodnie paladyna II',
            description: 'Dodają 6 pancerza',
            image: 'assets/images/512px_items/spodnie/set_2/s2.jpg',
            classItem: ItemTypeModel.pants,
            price: 15,
            armour: 6,
            itemRarity: 'uncommon',
            upgradePrice: 20,
            numerZestawu: 2),
        Rarity.rare: ItemModel(
            name: 'Spodnie paladyna III',
            description: 'Dodają 8 pancerza',
            image: 'assets/images/512px_items/spodnie/set_2/s3.jpg',
            classItem: ItemTypeModel.pants,
            price: 20,
            armour: 8,
            itemRarity: 'rare',
            upgradePrice: 20,
            numerZestawu: 2),
        Rarity.epic: ItemModel(
            name: 'Spodnie paladyna IV',
            description: 'Dodają 10 pancerza',
            image: 'assets/images/512px_items/spodnie/set_2/s4.jpg',
            classItem: ItemTypeModel.pants,
            price: 25,
            armour: 10,
            itemRarity: 'epic',
            upgradePrice: 20,
            numerZestawu: 2),
        Rarity.legendary: ItemModel(
            name: 'Spodnie paladyna V',
            description: 'Dodają 15 pancerza',
            image: 'assets/images/512px_items/spodnie/set_2/s5.jpg',
            classItem: ItemTypeModel.pants,
            price: 50,
            armour: 15,
            itemRarity: 'legendary',
            upgradePrice: 20,
            numerZestawu: 2),
        Rarity.mithic: ItemModel(
            name: 'Spodnie paladyna VI',
            description: 'Dodają 20 pancerza',
            image: 'assets/images/512px_items/spodnie/set_2/s6.jpg',
            classItem: ItemTypeModel.pants,
            price: 100,
            armour: 20,
            itemRarity: 'mithic',
            upgradePrice: 20,
            numerZestawu: 2),
      },
      ItemTypeModel.boots: {
        Rarity.common: ItemModel(
            name: 'Buty paladyna I',
            description: 'Dodają 1 pancerza',
            image: 'assets/images/512px_items/buty/set_2/b1.png',
            classItem: ItemTypeModel.boots,
            price: 10,
            armour: 1,
            itemRarity: 'common',
            upgradePrice: 20,
            numerZestawu: 2),
        Rarity.uncommon: ItemModel(
            name: 'Buty paladyna II',
            description: 'Dodają 3 pancerza',
            image: 'assets/images/512px_items/buty/set_2/b2.png',
            classItem: ItemTypeModel.boots,
            price: 15,
            armour: 3,
            itemRarity: 'uncommon',
            upgradePrice: 20,
            numerZestawu: 2),
        Rarity.rare: ItemModel(
            name: 'Buty paladyna III',
            description: 'Dodają 5 pancerza',
            image: 'assets/images/512px_items/buty/set_2/b3.png',
            classItem: ItemTypeModel.boots,
            price: 20,
            armour: 5,
            itemRarity: 'rare',
            upgradePrice: 20,
            numerZestawu: 2),
        Rarity.epic: ItemModel(
            name: 'Buty paladyna IV',
            description: 'Dodają 7 pancerza',
            image: 'assets/images/512px_items/buty/set_2/b4.png',
            classItem: ItemTypeModel.boots,
            price: 25,
            armour: 7,
            itemRarity: 'epic',
            upgradePrice: 20,
            numerZestawu: 2),
        Rarity.legendary: ItemModel(
            name: 'Buty paladyna V',
            description: 'Dodają 10 pancerza',
            image: 'assets/images/512px_items/buty/set_2/b5.png',
            classItem: ItemTypeModel.boots,
            price: 50,
            armour: 10,
            itemRarity: 'legendary',
            upgradePrice: 20,
            numerZestawu: 2),
        Rarity.mithic: ItemModel(
            name: 'Buty paladyna VI',
            description: 'Dodają 15 pancerza',
            image: 'assets/images/512px_items/buty/set_2/b6.png',
            classItem: ItemTypeModel.boots,
            price: 100,
            armour: 15,
            itemRarity: 'mithic',
            upgradePrice: 20,
            numerZestawu: 2),
      }
    },
    //--
    //set - 3 zestaw smoka
    //--
    ItemSet.set3: {
      ItemTypeModel.sword: {
        Rarity.common: ItemModel(
            name: 'Miecz smoka I',
            description: 'Dodaje 4 do ataku',
            image: 'assets/images/512px_items/miecze/set_3/m1.png',
            classItem: ItemTypeModel.sword,
            price: 10,
            attack: 4,
            itemRarity: 'common',
            upgradePrice: 20,
            numerZestawu: 3),
        Rarity.uncommon: ItemModel(
            name: 'Miecz smoka II',
            description: 'Dodaje 5 do ataku',
            image: 'assets/images/512px_items/miecze/set_3/m2.png',
            classItem: ItemTypeModel.sword,
            price: 15,
            attack: 5,
            itemRarity: 'uncommon',
            upgradePrice: 20,
            numerZestawu: 3),
        Rarity.rare: ItemModel(
            name: 'Miecz smoka III',
            description: 'Dodaje 6 do ataku',
            image: 'assets/images/512px_items/miecze/set_3/m3.jpg',
            classItem: ItemTypeModel.sword,
            price: 20,
            attack: 6,
            itemRarity: 'rare',
            upgradePrice: 20,
            numerZestawu: 3),
        Rarity.epic: ItemModel(
            name: 'Miecz smoka IV',
            description: 'Dodaje 7 do ataku',
            image: 'assets/images/512px_items/miecze/set_3/m4.png',
            classItem: ItemTypeModel.sword,
            price: 25,
            attack: 7,
            itemRarity: 'epic',
            upgradePrice: 20,
            numerZestawu: 3),
        Rarity.legendary: ItemModel(
            name: 'Miecz smoka V',
            description: 'Dodaje 10 do ataku',
            image: 'assets/images/512px_items/miecze/set_3/m5.png',
            classItem: ItemTypeModel.sword,
            price: 50,
            attack: 10,
            itemRarity: 'legendary',
            upgradePrice: 20,
            numerZestawu: 3),
        Rarity.mithic: ItemModel(
            name: 'Miecz smoka VI',
            description: 'Dodaje 15 do ataku',
            image: 'assets/images/512px_items/miecze/set_3/m6.jpg',
            classItem: ItemTypeModel.sword,
            price: 100,
            attack: 15,
            itemRarity: 'mithic',
            upgradePrice: 20,
            numerZestawu: 3),
      },
      ItemTypeModel.helmet: {
        Rarity.common: ItemModel(
            name: 'Chełm smoka I',
            description: 'Dodaje 3 pancerza',
            image: 'assets/images/512px_items/hełmy/set_3/h1.png',
            classItem: ItemTypeModel.helmet,
            price: 10,
            armour: 3,
            itemRarity: 'common',
            upgradePrice: 20,
            numerZestawu: 3),
        Rarity.uncommon: ItemModel(
            name: 'Chełm smoka II',
            description: 'Dodaje 5 pancerza',
            image: 'assets/images/512px_items/hełmy/set_3/h2.jpeg',
            classItem: ItemTypeModel.helmet,
            price: 15,
            armour: 5,
            itemRarity: 'uncommon',
            upgradePrice: 20,
            numerZestawu: 3),
        Rarity.rare: ItemModel(
            name: 'Chełm smoka III',
            description: 'Dodaje 7 pancerza',
            image: 'assets/images/512px_items/hełmy/set_3/h3.jpeg',
            classItem: ItemTypeModel.helmet,
            price: 20,
            armour: 7,
            itemRarity: 'rare',
            upgradePrice: 20,
            numerZestawu: 3),
        Rarity.epic: ItemModel(
            name: 'Chełm smoka IV',
            description: 'Dodaje 9 pancerza',
            image: 'assets/images/512px_items/hełmy/set_3/h4.jpeg',
            classItem: ItemTypeModel.helmet,
            price: 25,
            armour: 9,
            itemRarity: 'epic',
            upgradePrice: 20,
            numerZestawu: 3),
        Rarity.legendary: ItemModel(
            name: 'Chełm smoka V',
            description: 'Dodaje 15 pancerza',
            image: 'assets/images/512px_items/hełmy/set_3/h5.jpg',
            classItem: ItemTypeModel.helmet,
            price: 50,
            armour: 15,
            itemRarity: 'legendary',
            upgradePrice: 20,
            numerZestawu: 3),
        Rarity.mithic: ItemModel(
            name: 'Chełm smoka VI',
            description: 'Dodaje 20 pancerza',
            image: 'assets/images/512px_items/hełmy/set_3/h6.jpg',
            classItem: ItemTypeModel.helmet,
            price: 100,
            armour: 20,
            itemRarity: 'mithic',
            upgradePrice: 20,
            numerZestawu: 3),
      },
      ItemTypeModel.chestplate: {
        Rarity.common: ItemModel(
            name: 'Napierśnik smoka I',
            description: 'Dodaje 8 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_3/n1.jpg',
            classItem: ItemTypeModel.chestplate,
            price: 10,
            armour: 8,
            itemRarity: 'common',
            upgradePrice: 20,
            numerZestawu: 3),
        Rarity.uncommon: ItemModel(
            name: 'Napierśnik smoka II',
            description: 'Dodaje 10 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_3/n2.jpg',
            classItem: ItemTypeModel.chestplate,
            price: 15,
            armour: 10,
            itemRarity: 'uncommon',
            upgradePrice: 20,
            numerZestawu: 3),
        Rarity.rare: ItemModel(
            name: 'Napierśnik smoka III',
            description: 'Dodaje 12 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_3/n3.jpg',
            classItem: ItemTypeModel.chestplate,
            price: 20,
            armour: 12,
            itemRarity: 'rare',
            upgradePrice: 20,
            numerZestawu: 3),
        Rarity.epic: ItemModel(
            name: 'Napierśnik smoka IV',
            description: 'Dodaje 14 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_3/n4.jpg',
            classItem: ItemTypeModel.chestplate,
            price: 25,
            armour: 14,
            itemRarity: 'epic',
            upgradePrice: 20,
            numerZestawu: 3),
        Rarity.legendary: ItemModel(
            name: 'Napierśnik smoka V',
            description: 'Dodaje 20 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_3/n5.png',
            classItem: ItemTypeModel.chestplate,
            price: 50,
            armour: 20,
            itemRarity: 'legendary',
            upgradePrice: 20,
            numerZestawu: 3),
        Rarity.mithic: ItemModel(
            name: 'Napierśnik smoka VI',
            description: 'Dodaje 25 pancerza',
            image: 'assets/images/512px_items/napierśniki/set_3/n6.png',
            classItem: ItemTypeModel.chestplate,
            price: 100,
            armour: 25,
            itemRarity: 'mithic',
            upgradePrice: 20,
            numerZestawu: 3),
      },
      ItemTypeModel.pants: {
        Rarity.common: ItemModel(
            name: 'Spodnie smoka I',
            description: 'Dodają 4 pancerza',
            image: 'assets/images/512px_items/spodnie/set_3/s1.jpg',
            classItem: ItemTypeModel.pants,
            price: 10,
            armour: 4,
            itemRarity: 'common',
            upgradePrice: 20,
            numerZestawu: 3),
        Rarity.uncommon: ItemModel(
            name: 'Spodnie smoka II',
            description: 'Dodają 6 pancerza',
            image: 'assets/images/512px_items/spodnie/set_3/s2.jpg',
            classItem: ItemTypeModel.pants,
            price: 15,
            armour: 6,
            itemRarity: 'uncommon',
            upgradePrice: 20,
            numerZestawu: 3),
        Rarity.rare: ItemModel(
            name: 'Spodnie smoka III',
            description: 'Dodają 8 pancerza',
            image: 'assets/images/512px_items/spodnie/set_3/s3.png',
            classItem: ItemTypeModel.pants,
            price: 20,
            armour: 8,
            itemRarity: 'rare',
            upgradePrice: 20,
            numerZestawu: 3),
        Rarity.epic: ItemModel(
            name: 'Spodnie smoka IV',
            description: 'Dodają 10 pancerza',
            image: 'assets/images/512px_items/spodnie/set_3/s4.jpg',
            classItem: ItemTypeModel.pants,
            price: 25,
            armour: 10,
            itemRarity: 'epic',
            upgradePrice: 20,
            numerZestawu: 3),
        Rarity.legendary: ItemModel(
            name: 'Spodnie smoka V',
            description: 'Dodają 15 pancerza',
            image: 'assets/images/512px_items/spodnie/set_3/s5.jpg',
            classItem: ItemTypeModel.pants,
            price: 50,
            armour: 15,
            itemRarity: 'legendary',
            upgradePrice: 20,
            numerZestawu: 3),
        Rarity.mithic: ItemModel(
            name: 'Spodnie smoka VI',
            description: 'Dodają 20 pancerza',
            image: 'assets/images/512px_items/spodnie/set_3/s6.jpg',
            classItem: ItemTypeModel.pants,
            price: 100,
            armour: 20,
            itemRarity: 'mithic',
            upgradePrice: 20,
            numerZestawu: 3),
      },
      ItemTypeModel.boots: {
        Rarity.common: ItemModel(
            name: 'Buty smoka I',
            description: 'Dodają 1 pancerza',
            image: 'assets/images/512px_items/buty/set_3/b1.jpg',
            classItem: ItemTypeModel.boots,
            price: 10,
            armour: 1,
            itemRarity: 'common',
            upgradePrice: 20,
            numerZestawu: 3),
        Rarity.uncommon: ItemModel(
            name: 'Buty smoka II',
            description: 'Dodają 3 pancerza',
            image: 'assets/images/512px_items/buty/set_3/b2.jpg',
            classItem: ItemTypeModel.boots,
            price: 15,
            armour: 3,
            itemRarity: 'uncommon',
            upgradePrice: 20,
            numerZestawu: 3),
        Rarity.rare: ItemModel(
            name: 'Buty smoka III',
            description: 'Dodają 5 pancerza',
            image: 'assets/images/512px_items/buty/set_3/b3.jpg',
            classItem: ItemTypeModel.boots,
            price: 20,
            armour: 5,
            itemRarity: 'rare',
            upgradePrice: 20,
            numerZestawu: 3),
        Rarity.epic: ItemModel(
            name: 'Buty smoka IV',
            description: 'Dodają 7 pancerza',
            image: 'assets/images/512px_items/buty/set_3/b4.jpg',
            classItem: ItemTypeModel.boots,
            price: 25,
            armour: 7,
            itemRarity: 'epic',
            upgradePrice: 20,
            numerZestawu: 3),
        Rarity.legendary: ItemModel(
            name: 'Buty smoka V',
            description: 'Dodają 10 pancerza',
            image: 'assets/images/512px_items/buty/set_3/b5.jpg',
            classItem: ItemTypeModel.boots,
            price: 50,
            armour: 10,
            itemRarity: 'legendary',
            upgradePrice: 20,
            numerZestawu: 3),
        Rarity.mithic: ItemModel(
            name: 'Buty smoka VI',
            description: 'Dodają 15 pancerza',
            image: 'assets/images/512px_items/buty/set_3/b6.jpg',
            classItem: ItemTypeModel.boots,
            price: 100,
            armour: 15,
            itemRarity: 'mithic',
            upgradePrice: 20,
            numerZestawu: 3),
      }
    },
};

  ItemModel getItem(ItemSet itemSet, ItemTypeModel itemType, Rarity rarity) {
    return _mapItems[itemSet]![itemType]![rarity]!;
  }

  bool isItemMaxLevel(int level, Rarity rarity) {
    if (level == maxLevelCommon && rarity == Rarity.common ||
        level == maxLevelUncommon && rarity == Rarity.uncommon ||
        level == maxLevelRare && rarity == Rarity.rare ||
        level == maxLevelEpic && rarity == Rarity.epic ||
        level == maxLevelLegendary && rarity == Rarity.legendary) {
      return true;
    }
    return false;
  }

  String getMaxLevel(Rarity rarity) {
    if (rarity == Rarity.common) {
      return maxLevelCommon.toString();
    } else if (rarity == Rarity.uncommon) {
      return maxLevelUncommon.toString();
    } else if (rarity == Rarity.rare) {
      return maxLevelRare.toString();
    } else if (rarity == Rarity.epic) {
      return maxLevelEpic.toString();
    } else if (rarity == Rarity.legendary) {
      return maxLevelLegendary.toString();
    } else {
      return 'Nielimitowany';
    }
  }
}